### ISSUE TITLE
tls block for ingress on librephotos chart?

### ISSUE THREAD

**Issue by loeken** [varet80/publiccharts#4]
was trying the chart and noticed there is no way to enable tls on the ingress usually i d expect something a long the lines of
```
  tls:
    {{- range $values.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ tpl . $ | quote }}
        {{- end }}
      {{- if .secretName }}
      secretName: {{ tpl .secretName $ | quote}}
      {{- end }}
    {{- end }}
  {{- end }}
```

as part of the ingress and helm values something like 
```
ingress:
  ...
  tls:
  - secretName: librephotos-tls
    hosts:
    - librephotos.example.com
```
any plans to add?
